name: CI/CD Pipeline for FastAPI using Actions

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Pull the Docker image from Docker Hub
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

        # Run the Docker container
      - name: Deploy FastAPI App
        run: |
          if [ $(docker ps -q -f name=fastapi-container) ]; then
            echo "Stopping existing container..."
            docker stop fastapi-container
          fi

          if [ $(docker ps -aq -f name=fastapi-container) ]; then
            echo "Removing existing container..."
            docker rm fastapi-container
          fi

          echo "Running the new container..."
          # docker run -d --name fastapi-container -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
